name: DCS
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - audioread=2.1.8
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cycler=0.10.0
  - cython=0.29.17
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.2.2
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.63.1
  - gmp=6.1.2
  - gnutls=3.6.5
  - icu=58.2
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - lame=3.100
  - libcxx=10.0.0
  - libedit=3.1.20181209
  - libffi=3.3
  - libflac=1.3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libogg=1.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - librosa=0.7.2
  - libsndfile=1.0.28
  - libsodium=1.0.16
  - libtiff=4.1.0
  - libvorbis=1.3.6
  - libvpx=1.7.0
  - llvm-openmp=10.0.0
  - llvmlite=0.31.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - nettle=3.4.1
  - notebook=6.0.3
  - numba=0.48.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1g
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=8.0
  - resampy=0.2.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.4.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tbb=2020.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - x264=1!157.20191217
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - astunparse==1.6.3
    - cachetools==4.1.0
    - chardet==3.0.4
    - crepe==0.0.11
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.15.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.29.0
    - h5py==2.10.0
    - hmmlearn==0.2.3
    - idna==2.9
    - imageio==2.8.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - keras-preprocessing==1.1.2
    - lxml==4.5.1
    - markdown==3.2.2
    - mido==1.2.9
    - mir-eval==0.6
    - music21==5.7.2
    - nbstripout==0.3.7
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - pretty-midi==0.2.9
    - protobuf==3.12.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pysoundfile==0.9.0.post1
    - pyyaml==5.3.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - urllib3==1.25.9
    - vamp==1.1.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
